FROM python:3.11-slim

RUN pip install --no-cache-dir dbt-postgres==1.7.* psycopg2-binary && \
    apt-get update && apt-get install -y --no-install-recommends postgresql-client && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/app
